"""
Trains the interpretable model used by the web dashboard and exports:
  - logistic regression coefficients (so the browser can score customers)
  - compact per-customer rows (so the browser can filter/aggregate live)
Output: dashboard/data.js
"""
import json
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score

df = pd.read_csv("data/Telco-Customer-Churn.csv")
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce").fillna(0)

y = (df["Churn"] == "Yes").astype(int)

# ---- Feature set chosen to be enterable by a human in a form ----
# (TotalCharges is deliberately excluded: it is essentially tenure x MonthlyCharges,
#  and asking a user for it would be redundant.)
feat = pd.DataFrame({
    "tenure": df["tenure"],
    "MonthlyCharges": df["MonthlyCharges"],
    "SeniorCitizen": df["SeniorCitizen"],
    "Partner": (df["Partner"] == "Yes").astype(int),
    "Dependents": (df["Dependents"] == "Yes").astype(int),
    "PaperlessBilling": (df["PaperlessBilling"] == "Yes").astype(int),
    "Contract_OneYear": (df["Contract"] == "One year").astype(int),
    "Contract_TwoYear": (df["Contract"] == "Two year").astype(int),
    "Internet_Fiber": (df["InternetService"] == "Fiber optic").astype(int),
    "Internet_No": (df["InternetService"] == "No").astype(int),
    "TechSupport_Yes": (df["TechSupport"] == "Yes").astype(int),
    "OnlineSecurity_Yes": (df["OnlineSecurity"] == "Yes").astype(int),
    "Payment_ElectronicCheck": (df["PaymentMethod"] == "Electronic check").astype(int),
})

X_train, X_test, y_train, y_test = train_test_split(
    feat, y, test_size=0.2, random_state=42, stratify=y)

scaler = StandardScaler().fit(X_train)
model = LogisticRegression(max_iter=1000).fit(scaler.transform(X_train), y_train)

pred = model.predict(scaler.transform(X_test))
proba = model.predict_proba(scaler.transform(X_test))[:, 1]
acc = accuracy_score(y_test, pred)
auc = roc_auc_score(y_test, proba)
print(f"Dashboard model -> accuracy: {acc:.3f} | ROC-AUC: {auc:.3f}")

model_export = {
    "features": list(feat.columns),
    "mean": scaler.mean_.tolist(),
    "scale": scaler.scale_.tolist(),
    "coef": model.coef_[0].tolist(),
    "intercept": float(model.intercept_[0]),
    "accuracy": round(float(acc), 3),
    "auc": round(float(auc), 3),
}

# ---- Compact per-customer rows for live filtering in the browser ----
# order: tenure, monthlyCharges, contract(0=M2M,1=1yr,2=2yr),
#        internet(0=DSL,1=Fiber,2=No), techSupport(0/1), churn(0/1)
contract_map = {"Month-to-month": 0, "One year": 1, "Two year": 2}
internet_map = {"DSL": 0, "Fiber optic": 1, "No": 2}
rows = [[
    int(r.tenure),
    round(float(r.MonthlyCharges), 2),
    contract_map[r.Contract],
    internet_map[r.InternetService],
    1 if r.TechSupport == "Yes" else 0,
    1 if r.Churn == "Yes" else 0,
] for r in df.itertuples()]

summary = {
    "total": int(len(df)),
    "churnRate": round(float((df["Churn"] == "Yes").mean() * 100), 1),
    "avgMonthly": round(float(df["MonthlyCharges"].mean()), 2),
    "monthlyRevenueAtRisk": round(float(df.loc[df["Churn"] == "Yes", "MonthlyCharges"].sum()), 0),
}
print("Summary:", summary)

import os
os.makedirs("dashboard", exist_ok=True)
with open("dashboard/data.js", "w", encoding="utf-8") as f:
    f.write("// Generated by export_for_dashboard.py - do not edit by hand\n")
    f.write("const MODEL = " + json.dumps(model_export) + ";\n")
    f.write("const SUMMARY = " + json.dumps(summary) + ";\n")
    f.write("const ROWS = " + json.dumps(rows, separators=(",", ":")) + ";\n")

print("WROTE dashboard/data.js")
